### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by revjkramer** [dortania/Opencore-Legacy-Patcher#10]
I have used Dosdudes install for Catalina on a Kepler Card Nvidia GT720 on a MacPro 3,1. It has always worked (once it loads the metal drivers) but I am getting no video with it or with the old stock gt 120 card.

At least with the GT 120 I can get to the OpenCore picker, but then it starts booting and then goes black and stays that way. Any idea? Is this do to the patcher, or Something else?

**Comment by khronokernel** [comment]
Are you able to upload the EFI the patcher built for your machine?

**Comment by revjkramer** [comment]
Yeah, that is with the patcher.

**Comment by revjkramer** [comment]
I hold command and then select my Macintosh HD which doesn't use the OpenCore EFI. SO I can get into the system. 2 separate partitions. One to keep what I have and one to boot OpenCore.

**Comment by priezz** [comment]
I have exactly the same issue. The only difference is that it is Mac Pro 4,1 with Nvidia GTX 780 Ti installed. Before installing Big Sur macOS was booting normally (with no boot screen visible). Now there is no video output at all (no signal to display). I know that Mac boots because I can connect remotely. To install OpenCode I used the old GT 120 card as well.
