### ISSUE TITLE
Legacy patcher 0.0.18 on MacMini 6,1 not working 

### ISSUE THREAD

**Issue by mistykasumi** [dortania/OpenCore-Legacy-Patcher#103]
Hi,

following the bricking incidents I have decided to upgrade my opencore installation to 0.6.8. However, having downloaded 0.0.18 and running the opencore upgrade, my mac has somehow reverted to catalina and seems to be totally ignoring opencore. I can't get into boot menu and catalina reports 6,1 as if opencore isn't being used. I did not see any obvious errors while running the patcher. Please advise how I can assist in debugging this.

**Comment by khronokernel** [comment]
I assume you ensured you selected EFI Boot in the Mac's boot picker correct? ie. holding Option key and selecting the EFI Boot with the Patcher logo like described in the [guide](https://dortania.github.io/OpenCore-Legacy-Patcher/BOOT.html)?

![](https://dortania.github.io/OpenCore-Legacy-Patcher/assets/img/efi-boot.8eb4fc48.png)

**Comment by mistykasumi** [comment]
for some reason, holding the option key (or ESC) does absolutely nothing. I have printouts running before that and afterwards but never a prompt.

**Comment by khronokernel** [comment]
Unfortunately if you can't load the Mac Boot Picker, there's little we can do to help. If SIP is disabled, you can however bless OpenCore with the following:

```
sudo bless --verbose --file /Volumes/VOLNAME/EFI/OC/OpenCore.efi --folder /Volumes/VOLNAME/EFI/OC --setBoot
```
You will need the partition OpenCore is installed on to be mounted, easiest way to do so is via [MountEFI](https://github.com/corpnewt/MountEFI).

Otherwise, if there's any patcher related issues do comment and we can re-open this issue
