### ISSUE TITLE
Firmware Recovery doubt 

### ISSUE THREAD

**Issue by CuchoM** [dortania/OpenCore-Legacy-Patcher#109]
**Describe the bug**
There is no bug just a question about firmware.
I've made a backup firmware 
sudo /usr/libexec/firmwarecheckers/eficheck/eficheck --save -b ~/firmware.bin

Then I used UEFItool to see inside and I found OCLP description see in the picture

Is it possible to upload the firmware and make native support with this command?

sudo bless -mount / -firmware <PATH>/firmware.bin --verbose --recovery
![Captura de ecrã 2021-03-20, às 10 26 15](https://user-images.githubusercontent.com/72659668/111866734-7a371880-8967-11eb-8bbd-c353cf499e3d.png)

**Comment by khronokernel** [comment]
>  I found OCLP description see in the picture

It's simply an NVRAM var we add on boot, no different from a user adding `-v` to boot-args, the GUID in question is actually [OpenCore's standard GUID](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Acidanthera/Guid/OcVariable.h#L102-L103) and we simply set `OCLP-Version` for debugging purposes. The rest of the vars are actually set by OpenCore itself. Running the following in terminal will list different properties:

```sh
# Original Model (ie. Before spoof)
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product
```

```sh
# OCLP Version set when building OpenCore
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:OCLP-Version
```

```sh
# Lists OpenCore version
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
```

These variables are not permanent whatsoever, a simple NVRAM reset will remove them and won't be re-added until you boot OpenCore again.

> Is it possible to upload the firmware and make native support with this command?
> `sudo bless -mount / -firmware /firmware.bin --verbose --recovery`

If you're asking whether we could support firmware restores via OpenCore that would be actually impossible due to the number of vars OpenCore writes and OCLP relies on (ie.`oem-product` ). Simply do it in your supported OS without OpenCore and a clean NVRAM slate, in all honesty I don't really see a reason for a user to need to backup their firmware while using OpenCore. Though I'm kinda impressed Apple botched it enough to keep non-Apple GUIDs in their firmware backups.
