### ISSUE TITLE
Unable to use > 60Hz displays on HDMI

### ISSUE THREAD

**Issue by Stig124** [dortania/OpenCore-Legacy-Patcher#129]
**Describe the bug**

Unable to use > 60Hz displays on HDMI
**To Reproduce**
1. Plug a display in HDMI to a > 60Hz display
2. Go to `System Prefs. - Display`
3. See that only 60 and 50Hz are available
4. Plug the same display in DisplayPort and the 100Hz will unlock
NOTE : Was working fine on 10.15.7, and a PC (on Kubuntu 20.04 and Windows 10) has no issue whatsoever swictching to 144Hz (I'm fine with 100Hz though)

**Hardware (please complete the following information):**
 - OS Running : 11.2.2, Big Sur (latest officially supported version 10.15.7 running fine at 100Hz)
 - OS Patching : 11.2.2, Big Sur
 - Model Patching : Mac Mini 6,1 (Late 2012)

**Additional context**
I don't know if this is related to the patcher at all

**Comment by khronokernel** [comment]
Unfortunately this sounds like a Big Sur bug and not a patcher bug, Apple's been having a lot of issues with display output on both Intel and Apple Silicon. The biggest issue is that it's not consistent user to user. Some users reported that the displays became problematic with 11.1 and newer, could try using an older build if you're able to find one still hosted. 

Otherwise, we're not really able to do much as a patcher until it's resolved by Apple. I would recommend running Displayport if possible, this is what seems to avoid most issues for users
