### ISSUE TITLE
Snow Leopard booting working!

### ISSUE THREAD

**Issue by borp99** [dortania/OpenCore-Legacy-Patcher#154]
Hi, your guide states that OCLP is for 10.7-11. However, I have OCLP 0.0.22 installed on a cMP3,1 I'm currently fitting out to gift to my sister and it's booting 10.6.8 just fine. I don't think I did any particular patching (in software, anyway - although have upgrading the wifi card to a BCM94331CD, and have an HD7950 with Mac EFI as a graphics card). I was previously using rEFInd to boot into Snow Leopard. As OCLP just 'worked' after I installed it, I didn't assume it was possibly unsupported. Maybe other classic Macs (eg. MBP's) can't boot 10.6.8 with OCLP from your experience, so that's why you aren't stating that it's generally possible. 

I only have 10.6.8 on a partition in case she needs to run any UB PowerPC apps under Rosetta 1.0 or 32 bit audio plugins. Mac OS 10.12, 10.15 and 11.2.3 are on other partitions and running very well. Thank you for all of your efforts to keep these old - but still good - computers viable. My main mac is a 5,1 dual 3.46GHz machine (you may be interested that I gutted the inside fan cage and replaced CPU cooling with horizontally oriented heatsinks and fans / the stock fan cage constantly hummed very loudly at E13 major, which drove me crazy, as I'm an orchestral musician by trade).

**Comment by khronokernel** [comment]
Good to hear! Main reason we say we only work on 10.7-11 is due to an issue with our python script crashing when running "Install OpenCore to disk". Additionally, the macOS 11 support for OpenCore itself is mostly a SMBIOS issue as we want users to know that the new SMBIOS applied may not play nicely on all older OSes and is mostly a catch all for when issues do occur
