### ISSUE TITLE
Can't put computer to sleep

### ISSUE THREAD

**Issue by laxamar** [dortania/OpenCore-Legacy-Patcher#172]
Successfully used the patchter to install FRESH and upgraded Big Sur systems. Neither on the Mac Pro nor the iMac, can I get the systems to go to sleep. Neither with timeout nor by choosing the "Sleep" menu option,

**To Reproduce**
Just get to Big Sur following patcher instruction and either upgrade or install a clean system. I have tried all the power/wifi/bluetooth instructions/suggestions I could find on the web.

**Hardware (please complete the following information):**
 - OS 11.2.3, Big Sur
 - iMac Late 2010 & Macbook Pro Late 2011

**Additional context**
The systems are VERY responsive until screen saver kicks in, then everything goes very slow. The sleep feature never works

**Comment by khronokernel** [comment]
Did you enable GPU Acceleration Patches? ie. Post Install Volume Patches

**Comment by laxamar** [comment]
> Did you enable GPU Acceleration Patches? ie. Post Install Volume Patches

Not sure what you mean. From [https://dortania.github.io/OpenCore-Legacy-Patcher/PATCHEXPLAIN.html#opencore-settings](url)? Audio is working and graphics are really fast on boot. Did I miss something?

**Comment by khronokernel** [comment]
I'm asking specifically that you ran the "Post-Install Volume Patch" from OCLP after you finished installing Big Sur. Just ensuring you have proper graphics acceleration.

Additionally, are these clean installs of Big Sur? No one has reported sleep issues with 11.2.3 on any legacy GPU, hinting that your issue is most likely a program or background task preventing the machine from sleeping. I would recommend checking Activity Monitor whether any apps report True in the "Preventing Sleep" column:

<img width="1182" alt="Screen Shot 2021-04-27 at 4 16 26 PM" src="https://user-images.githubusercontent.com/48863253/116319559-f5b09480-a773-11eb-859b-d2514892d25c.png">

**Comment by laxamar** [comment]
OK!
The script had an extra step I missed. One of the systems is a clean install on a fresh drive. So the OCLP wasn't on it ..

I will run the that next step and post results here for anybody else who missed the step.

Thanks

**Comment by laxamar** [comment]
Sleep now works ... but top menu disappeared!!!
Can't see apple menu nor use it. This is on an upgrade iMac. Clean install Macbookpro still not rebooting ..

![Screen Shot 2021-04-27 at 4 09 37 PM](https://user-images.githubusercontent.com/2382057/116323560-1d532d00-a773-11eb-902f-763b1917c477.png)

**Comment by laxamar** [comment]
CONFIRMED, even with version 0.1.1 - BigSur 11.2.x and 11.3, I lose the top banner after Post-Install Volume patch.

Any suggestions?

**Comment by khronokernel** [comment]
GPU Acceleration is currently in beta, expect visual glitches
