### ISSUE TITLE
windows 10 install won't work on iMac mid 2011

### ISSUE THREAD

**Issue by motor-cyber** [dortania/OpenCore-Legacy-Patcher#193]
windows won't let me install its not going trough uefi when I get in windows to choose a disk it say can't install format is uefi and If I format drive again it goes but crashes

**Comment by Ausdauersportler** [comment]
Thanks for double posting this on the iMac GPU thread. There are several methods published to install Windows UEFI on the iMac 2009-2011. Pick one and go ahead. Even on this thread there is in method linked in.

**Comment by khronokernel** [comment]
@Ausdauersportler Ah thank you for clarifying
@motor-cyber Yeah this isn't a general help forum. It's OCLP bugs or enhancements. Your issue is neither related to OCLP besides "UEFI" and honestly have done nothing to provide us with proper error messages, debug logs, etc. If you determine the issue is in fact caused by OCLP, we have no issue reopening this issue. But for Windows centric problems, we have no interest dedicating resources to solving. For 1, I don't even have Windows installed on any of my Macs. I simply wanted to add UEFI Windows audio support as it was something a few users had requested and provided resources to integrate
