### ISSUE TITLE
application that asks for camera or microphone access doesn't appear on Big Sur system preferences

### ISSUE THREAD

**Issue by paltrowlalic** [dortania/OpenCore-Legacy-Patcher#200]
Big Sur 11.3.1
iMac12,2
OCLP 0.1.1
Apps (Google Chrome or Microsoft Remote Desktop)

As it is described in the title, I cannot use the microphone/camera for any meetings. I did search a bit on the internet and it seems that many people have the same/similar issue with Catalina and BS. But there is no clear answer. What could be the reason for this and any possible solutions? Thanks.
![image](https://user-images.githubusercontent.com/19687506/117479313-163cd380-af58-11eb-9129-70ea6963e76a.png)

**Comment by paltrowlalic** [comment]
Found more info below. It seems that it is related to "amfi_get_out_of_my_way=1". So should I delete this arg or change it to a different value?

![image](https://user-images.githubusercontent.com/19687506/117482645-91a08400-af5c-11eb-9d61-a94b4a299ce9.png)

**Comment by khronokernel** [comment]
Unfortunately `amfi_get_out_of_my_way=1` is actually required for the OS to accept the new GPU Acceleration Frameworks without crashing. If you have a Metal GPU, the property is not required at all which seeing as you have an iMac12,2 I assume you did upgrade.

Though quite odd, OCLP should never disable SIP and set AMFI if it detects a Metal GPU. What version of OCLP are you running as well as what GPU?

**Comment by khronokernel** [comment]
Hmm could you verify if 0.1.2 has this issue as well? I was working with an iMac11,2 user with this problem which I though I resolved: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/e86b48e0fc12694b271fcb781a85aab8773b0985

The idea is that when a Metal GPU is present, SIP is automatically enabled

**Comment by paltrowlalic** [comment]
I tried 0.1.2 earlier today but the progress bar stuck in the middle so moved on to 0.1.1. I can try again now. Do you mean if I enable SIP, then there should no argument about amfi_get_out_of_my_way in the config file (since I am having a metal GPU)?

**Comment by khronokernel** [comment]
> Do you mean if I enable SIP, then there should no argument about amfi_get_out_of_my_way in the config file (since I am having a metal GPU)?

Well in patcher settings, SIP and AMFI should be omitted by default (ie. both set to true) if a Metal GPU is present. Regarding black screen, could you upload 0.1.2's EFI OCLP generated as well as 0.1.1? Would like to resolve these issues

**Comment by paltrowlalic** [comment]
Hi @khronokernel , I just tried 0.1.2 and this time no black screen issue at all. FYI, both SIP and SBM are set as True by default in 0.1.1 and 0.1.2. I changed both to False because I had problems before with SBM enabled (not booting into BS). If I leave SIP as true and just disable SBM now my apps have access to microphone and camera). So the problem is caused by the disabled SIP ->  mfi_get_out_of_my_way=1.  I think we can close this issue and thank you for the help! Again!

![image](https://user-images.githubusercontent.com/19687506/117491929-d205ff00-af68-11eb-8da6-c467a7eed6c4.png)
![image](https://user-images.githubusercontent.com/19687506/117492078-024d9d80-af69-11eb-9df1-2eec9c92afb8.png)
![image](https://user-images.githubusercontent.com/19687506/117492147-185b5e00-af69-11eb-8014-fdad4e61f49d.png)

**Comment by khronokernel** [comment]
Great to hear! I might as well explain a little bit about SBM/SecureBootModel so you'll at least know *why* it may be causing issues.

So SecureBootModel in a sense enables T2-level security by doing signature checks throughout the boot process. With macOS Big Sur, Apple actually allowed native, non-T2 models to gain this semi-secureboot feature. This is required for stable deltas and OTA updates, otherwise risking corruption and failed updates.

I assume with SecureBootModel enabled, you hit this issue:
```
OCB: LoadImage failed - Security Violation
```

This generally means either the signed SecureBoot files are missing or they've been corrupted/broken. This will actually occur with machines dual booting High Sierra as the older OS will corrupt the files upon loading the drive. 

So there's 3 solutions:
- Disable SBM and potentially risk a botched OTA update
- Reinstall Big Sur(to restore the signatures) and never use High Sierra
- Reinstall Big Sur(to restore the signatures) and remove the Big Sur drive when booting High Sierra

With an iMac, I would recommend just disabling SBM as unplugging the drive for troubleshooting is a bit of a pain with removing the screen and the screws when booting High Sierra

**Comment by paltrowlalic** [comment]
Thanks for the explanation. I do have HS and BS installed on two partitions but on the same drive. Do you think the SBM  problem will disappear if I have Catalina and BS on the same drive? I will give it try sometime later - too many times of OS installations recently : (
