### ISSUE TITLE
MacBookPro8,2/3 Display Sleep Wake Issues

### ISSUE THREAD

**Issue by guanzhangrtk** [dortania/OpenCore-Legacy-Patcher#220]
Hi, thanks for the software and also putting together the acceleration patches, it's great when an old laptop can get a breath of new life via third-party software.

I recently did a fresh install of Big Sur 11.3.1 on a MacBookPro8,2 via an external USB drive using OCLP 0.1.4. This machine has a busted AMD discrete GPU so I have disabled it using the `nvram` command in single user mode so it's just running the internal Intel HD Graphics 3000 card. There is slight delay with things but it's usable on a daily basis. Also I would suspect better performance once I install it onto the internal SSD drive.

However, there is an issue where after putting the machine to sleep and waking it up after extended periods of time, the display does not come back up. The external HD has a light and it was off during hibernation and after waking it up it does light up, so does the Bluetooth external keyboard so I know the machine was asleep and was woken up, it's just that there is no display whatsoever. Screen Sharing is enabled and RealVNC on iPad was able to connect to the machine via Bonjour. It prompted for password to access however was never able to fully log into the machine.

So the machine definitely got woken up, but just not fully, so I was wondering if other people have encountered the same issue.

Thanks for any feedback in advance!

**Comment by lulujyc** [comment]
Confirmed a similar issue installing OCLP patched Big Sur on a DGPU-disabled MacBookPro8,3. The system does not go to sleep at all, or hibernation, indicated by the sleep light.

**Comment by lulujyc** [comment]
The following is my test on my MBP8,3:

Using the default configuration as well as agdpmod=vit9696 boot arg, both Hibernation and Sleep failed to work, i.e. the Mac cannot enter ACPI S3 and S4. 

Using the -wegnoegpu boot arg, the Mac can enter both Hibernation and Sleep modes, but cannot wake on Sleep, showing a black screen. Wake on Hibernation works good.

Using the -wegnoegpu boot arg with igfxonln=1 doesn't fix the Wake on Sleep issue.

**Comment by airman1951** [comment]
My test: MBP8,2, BS 11.3.1 installed on internal SSD, OCLP 0.1.3, eGPU disabled.  I used the commands provided by Mykola to accelerate the hibernation. Test began at 12:20 and system went to sleep at 12:35 as expected.  I took my launch and came back 1 hour later. A single touch of the space bar woke up the system.
![Screenshot 2021-05-15 at 11 33 58](https://user-images.githubusercontent.com/77781242/118358978-7992bb00-b581-11eb-8ee7-4755242bfd8e.png)
![Screenshot 2021-05-15 at 11 34 33](https://user-images.githubusercontent.com/77781242/118358984-80b9c900-b581-11eb-9c94-b8022a7f021a.png)
![Screenshot 2021-05-15 at 13 23 53](https://user-images.githubusercontent.com/77781242/118359004-a1821e80-b581-11eb-8f52-6bb59e08ee8a.png)

**Comment by guanzhangrtk** [comment]
> My test: MBP8,2, BS 11.3.1 installed on internal SSD, OCLP 0.1.3, eGPU disabled. I used the commands provided by Mykola to accelerate the hibernation. Test began at 12:20 and system went to sleep at 12:35 as expected. I took my launch and came back 1 hour later. A single touch of the space bar woke up the system.

@airman1951 How did you disable the dGPU? Using the `nvram` command in RecoveryOS/single-user mode? And is the GPU functional or broken? Thanks!

**Comment by lulujyc** [comment]
My theory from discord:

There are two problems (of sleep) with dGPU disabled via NVRAM, first, brightness set to 0 after turned off, second, system KP after sleep
So I use -wegnoegpu to make dGPU invisible to OS
Now system no longer KP after sleep
With hibernation the first problem does not occur, the brightness is set to 100 after wake up
With sleep the brightness is set to 0 after wake up
But still the system won't KP after sleep because the dGPU has been fully disabled
^ This is my theory and result on my setup but please test if this worked for you

**Comment by guanzhangrtk** [comment]
Adding `-wegnoegpu` to `boot-args` and accelerating hibernation fixed it for me.

So to summarize, the issue only happens to folks who has a busted dGPU (either partial failure or full failure).

More specifically, the instructions are to first get [mountEFI](https://github.com/corpnewt/MountEFI) to mount up the EFI partition of the installation disk, then edit `/Volumes/EFI/EFI/OC/config.plist`, look for `boot-args` under `NVRAM` and add `-wegnoegpu` to the end so it'll look something like this: `<string>keepsyms=1 debug=0x100 amfi_get_out_of_my_way=1 -wegnoegpu</string>`.

To accelerate hibernation do this:

```
sudo pmset -a hibernatemode 25
sudo pmset -a standby 1
sudo pmset -a standbydelaylow 1
sudo pmset -a standbydelayhigh 1
```

Now the machine will wake up fully from hibernation with functional display. The screen may turn off/on/flicker a bit before fully working.

Now the question is is there a fix such that we can still sleep normally without going to hibernation?

Thanks @lulujyc

**Comment by NOTNlCE** [comment]
I tested with these folks on my systems as well and can report that this issue does NOT affect 8,2 MacBook Pros that have had the demux mod. Sleep works great and it wakes right up when the lid is opened on all four of my 8,2 systems.

**Comment by guanzhangrtk** [comment]
Okay looks like I'm not out of the woods yet. Laptop went idle -> hibernate and when I try to wake it back up I got backlight on the screen but otherwise no response. After hard shutdown/reboot, there seems to have been a panic (see [stracktrace](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6488090/panic.txt)).

**Comment by MrMacintoshBlog** [comment]
I just got my 2nd 8,2 up and running. Let me know if you need any help testing.

**Comment by lulujyc** [comment]
Problem fixed.

**Here's how I realized the fix:**
Ok I gave up using Sierra's AppleMuxControl
I think the only feasible way to mitigate the sleep issue was to again, not use -wegnoegpu, because you lose sleep and brightness control immediately
But to try to make it able to sleep with AMD drivers loaded
Even though if Sierra's AppleMuxControl can be worked with BS, No one knows if it will break in say macos 12, so this is not the way i want
I will revert to the build that has partial Terascale 2 support to experiment
I hate apple so much its literally creating tons of issues on purpuse to force you buy a new mac
won't do that :frowning:
Possible fixes imo: (1) write a backlight fixup kext that allows to change screen backlight: not 100% impossible as apple has made this a software-based problem since HS but very difficult; (2) use Sierra's AppleMuxControl which is a bad way to do and also very hard; (3) Force AMD drivers to load which is how most people dealt with the problem on Catalina before
The (2) way worked on Mojave but I see no success reports after 10.15; the (3) way worked on 10.15 after installing full acceleration patches but not on BS
Or alternatively... (4) solder some wires on the board or flash the mux firmware:joy:
I'm very wrong yesterday when I said that Brightness control is related to dGPU being Hardwired
It is not, and my best guess is that the drivers are checking if a functional dGPU is present
So this explains why Sleep and Brightness worked on Sierra before
Still need to check why sleep KP the OS with NVRAM disabled dGPU present
If this can be directly solved then the whole issue go away

**Here's the fix:**
Good news guys
I've fully fixed the Brightness and the Sleep natively
Also close lid to sleep
Without dealing with WEG
My theory on the (3) way is correct
Here're the steps
So first you need to clone this repo
https://github.com/dortania/OpenCore-Legacy-Patcher/tree/78038b9607d865c27f45bcda306c1c7d281ef454
Which is the one that has "Partial TeraScale 2 Support"
Although no acceleration can be expected, this is important for fixing sleep
After download, unzip and click into "ModelArray.py"
You need to make the 957 line     #"AMDRadeonX3000.kext",
Adding a # before X3000 kext
And right click on OpenCore-Patcher.command, use this version of OCLP to generate an OC EFI to avoid having boot-flags interfering with the GPU
Reboot
And use this version of OCLP to patch your OS, make sure now you can see both HD 3000 and AMD dGPU
And reboot
Now well done
This is the most vanilla fix, allowing for 100% Fully Working graphics, brightness and sleep that I spent two freaking days researching
Now enjoy it :)

**Comment by khronokernel** [comment]
@lulujyc Appreciate the testing! I've made a [new branch](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/terascale-2-test) relying on that old code with the `"AMDRadeonX3000.kext",` entry commented out. Any users interested can grab a build below:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2753505624/artifacts/60870514 (1799625)

**Comment by lulujyc** [comment]
> @lulujyc Appreciate the testing! I've made a [new branch](https://github.com/dortania/OpenCore-Legacy-Patcher/tree/terascale-2-test) relying on that old code with the `"AMDRadeonX3000.kext",` entry commented out. Any users interested can grab a build below:
> 
> https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2753505624/artifacts/60870514 ([1799625](https://github.com/dortania/OpenCore-Legacy-Patcher/commit/1799625f99d09626d22639ce0fe40ef4dd142302))

I'm trying to add an option to switch between patching AMD kext (for GPU defective macs) and not patching AMD kext (for deMUXed macs or non-defective MBP8,2/ MBP8,3). First time to python but I will try working on this😂

**Comment by khronokernel** [comment]
>  but I will try working on this

When you deMUX a Mac, the GFX0 entry disappears. Therefore OCLP should never run the AMD patches due to never detecting a dGPU:
https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/Resources/SysPatch.py#L115-L117

**Comment by khronokernel** [comment]
With the help of lulujyc, we've updated OCLP to properly detect when to patch AMD support back in:
```python
#- deMUX: Don't need the AMD patches
#- dGPUs enabled:  Don't install the AMD patches (Infinite login loop otherwise)
#- dGPUs disabled: Do need the AMD patches (Restores Brightness control)
```

Regarding the last entry, we detect whether the `gpu-power-prefs` variable is present and if so add the kexts

Can grab a binary below, will merge the branch into main shortly:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2753915054/artifacts/60887729
