### ISSUE TITLE
Error during Build Configuration

### ISSUE THREAD

**Issue by odetinin** [dortania/OpenCore-Legacy-Patcher#221]
I am trying to build configuration and getting this error. Please see attached image.

OS: Catalina 10.15.7
MacPro 3,1
OpenCore-Legacy: 0.1.4

![Screen Shot 2021-05-14 at 12 13 47 PM](https://user-images.githubusercontent.com/1234472/118298796-edfc2a00-b4ad-11eb-8bb8-7375629e6aec.png)

**Comment by khronokernel** [comment]
Hello, this should be resolved with 0.1.5. Can grab a build below:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2744546120/artifacts/60655014

I assume this machine has no wireless card correct? That's likely why it's crashing, which we fixed in 0.1.5 in commit https://github.com/dortania/OpenCore-Legacy-Patcher/commit/78760b8a0806c337d2bb60dcb84b8acc168e2e4c

**Comment by odetinin** [comment]
Thanks ! Yes, no wireless card.
