### ISSUE TITLE
MacPro 3,1  does not go to Sleep -- Big Sur 11.3.1

### ISSUE THREAD

**Issue by odetinin** [dortania/OpenCore-Legacy-Patcher#222]
Environment:

OpenCore-Legacy: 0.1.15 (beta)
OS: Big Sur 11.3.1
CPU: MacPro 3,1, No WiFi, Nvidia EVGA GTX 680 SC with 2GB and Flashed for Mac (Metal is supported)

When putting MacPro to sleep mode via Apple Menu option, machine "goes to sleep" for one second and after one blink immediately wakes up (displays are not). This cycle repeats itself indefinitely -- after some interval MacPro tries to sleep again and after one blink wakes up.

Some other points:
- Wake for ethernet network access is disabled
- In Activity Monitor no task is preventing sleep
- This is a FRESH installation of Big Sur with the only one program installed -- OpenCore-Legacy
- Only 2 USB devices are connected -- mouse and keyboard

**Comment by khronokernel** [comment]
We've had multiple users report success with MacPro3,1 with different configurations, this seems to be a user-configuration issue. Recommend debugging sleep wake reason with `pmset`. If you believe the issue is OpenCore Legacy Patcher, than I have no issue reopening this issue. However for user-configuration concerns, we have other issues that take precedence over this
