### ISSUE TITLE
add option to automatically enable OC picker audio

### ISSUE THREAD

**Issue by stas-prze** [dortania/OpenCore-Legacy-Patcher#235]
Hello.
I'm a blind user of OCLP.
Recently I noticed that you can enable picker audio assist which enables an accessible boot picker for you.
I find the process to enable the feature overwhelming and can't do it alone.
Is there a possibility of adding an automated script to OCLP that will do this?

**Comment by khronokernel** [comment]
For Legacy Macs, not possible due to the current audio drive in the Mac's firmware unable to use the AudioDxe.efi driver. Would need to attempt to disconnect and destroy the native driver which would be out of scope for OpenCore Legacy Patcher. Perhaps this can be discussed on Acidanthera's bug tracker as they maintain OpenCore itself:
https://github.com/acidanthera/bugtracker/issues
