### ISSUE TITLE
Big Sur setup breaks after 12minutes

### ISSUE THREAD

**Issue by Ency79** [dortania/OpenCore-Legacy-Patcher#244]
Hello
I have followed exactly the tutorial https://youtu.be/5M1MepotME0

i have a Late 2012 MacBook Pro 9,2.
Booting from usb drive I selected efi boot and followed the procedure. I also erased my whole macintosh HD. It started to install big sur and after 12 minutes I turned on black screen and rebooted. 

What can be the problem???

**Comment by khronokernel** [comment]
Sounds like failing hard drive, verify other drives cannot replicate

**Comment by tyjon31** [comment]
I ran into the same issue last night after multiple attempts.  I have an iMac 14,2 with 32GB of RAM and dedicated Nvidia graphics.  I followed the written documentation to create the install disk.  everything went smoothly enough until the Big Sur got to the 12 minutes left point at which the spinning circle appeared and the dreaded valid startup disk message came up.  The instructions did not explicitly advise this but I did wipe the PRAM with no success.  The 12 minute mark was consistent in the process failing.  My boot drive is a WD Blue 4TB SSD and am using SanDisk 64GB USB drives.  In my case this is not a drive failure.  Any other recommendations to troubleshoot the matter? Thank you.

**Comment by Ausdauersportler** [comment]
There is a [forum thread](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-28584549) for trouble shooting and exchange of experiences. 
In your case I would try a forced reboot after the 12 minutes left point and see how things work out. Lately the installers sometimes stuck in some kind of race conditions and installing versions since 11.3 became a bumpy process on some models (mostly iMac11,x). Never heard of problems with your system. And try to recreate the USB installer using different hardware. Let‘s move over to the thread.
