### ISSUE TITLE
iMac12,1 can't login after applying post-install patch for GPU acceleration (fresh 11.4 install)

### ISSUE THREAD

**Issue by crsleeth** [dortania/OpenCore-Legacy-Patcher#259]
**Describe the bug**
Fresh install of Big Sur 11.4 using OpenCore-Legacy-Patcher 0.1.6 on iMac12,1. After applying the post-install patch for GPU acceleration I can't log in. At the log in screen when I enter my password the screen goes to black with a cursor for a few seconds then kicks back to the login screen. iMac has i5-2400 with AMD Radeon HD 6750M.

**To Reproduce**
1. Fresh install of Big Sur 11.4 using OpenCore-Legacy-Patcher on iMac 12,1
2. Apply post-install patch
3. Can't log in

**Hardware (please complete the following information):**
 - OS Running: Big Sur 11.4
 - OS Patching: OpenCore-Legacy-Patcher 0.1.6
 - Model Patching: iMac12,1

**Comment by Ausdauersportler** [comment]
Right now there are no patches for the ATI 6000 series included. The 2011 MBP users have to disable the dGPU to get the HD3000 patches running. This is not an option for your system because the dGPU runs the internal screen. 

You are aware of this [thread](https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/post-17425857)? 

You will have to wait until the new patches go public or change your GPU.

**Comment by khronokernel** [comment]
Acceleration patches for TeraScale 2 are currently under development, unknown timeline currently for releasing
