### ISSUE TITLE
MacPro5,1 specific guide?

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#293]
I've noticed there are some special considerations for those of us on `MacPro5,1` and below systems that have variable GPUs. I've found myself having to use a legacy Nvidia Metal 1 supporting card to bring some sanity to my boot device selection process, but still hitting walls when going through this general guide.  

It seems that some special attention needs to go towards documenting the nuances of getting OCLP to work properly during installation with `MacPro5,1` and below systems in a reliable way.

Does any such effort or guide exist?

**Comment by khronokernel** [comment]
No reason for Mac Pros to have special documentation, just use OpenCore Legacy patcher normally

Could you elaborate on why Mac Pros need specific adjustments? All that's different is they support Metal GPU upgrades, but this doesn't change the patcher process at all

**Comment by ylluminate** [comment]
Apparently I've become the victim of the 11.3 breakage as per [this thread](https://forums.macrumors.com/threads/mac-os-11-3-has-broken-support-for-older-mac-pros.2289056/).  I suppose the real key is to mention this (eg, only use up to 11.2 if you have an MacPro6,1 and below).

One thing that could help is to understand if using a legacy Metal 1 card (such as an old Nvidia) with EFI boot support is essential for initial OpenCore boot selection or if the `option` key boot method *always* (or not) selects the attached USB boot volume that was just generated by OCLP during the build and USB install phase. If we were to know this with certainty it would prevent our needing to pop an old graphics card in during this process.

As an aside, is there an authoritative tracking point for this issue yet in the hunt for the real problem + work to resolve?

**Comment by cdf** [comment]
Due to the lack of preboot configuration support, booting and blessing OpenCore on a Mac Pro 5,1 with a standard graphics card requires special attention. The procedure is described in the [guide on MacRumors](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/) (see _First Boot_ in Part 1).

Note that without a Mac-EFI graphics card, holding the option key at boot will not bring up the Apple Startup Manager; it can't even be used "blindly." Also, while OpenCore may still happen to boot by default if nothing else is blessed, it will not actually be blessed. This situation can be problematic for boot selection routing.

**Comment by ylluminate** [comment]
This is golden information @cdf and I very much appreciate your articulation of these details. I've have now thought otherwise for YEARS and so this is invaluable information regarding the `option` boot selector!!!

I guess what we really need is a boot selection routing guide with all of the details and how to work with and around such a situation.  I have found that resetting the nvram via `cmd-opt-p-r` is also problematic in these cases and have been "bitten" multiple times by this without being able to boot sans an EFI card on hand...
