### ISSUE TITLE
Big Sur won't boot after applying post-install volume patch [Bug]: 

### ISSUE THREAD

**Issue by vicman777** [dortania/OpenCore-Legacy-Patcher#446]
### Machine Model

MacBookPro8,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

I installed everything including Big Sur and all patches  except the post-install volume patch and the mac worked great but would not sleep. I then added the post-install volume patch and clicked restart and the boot will not boot past a third of the process bar. It seems the post-install volume patch breaks something. Are you able to give advice to where I can look for where the issue is and even how to fix it.

P.S I have reinstalled a few times and get the same result.

**Comment by guanzhangrtk** [comment]
Hi, I have a similar issue with MacBookPro8,2 and had to revert back to OCLP 0.1.5 since the latest version of OCLP also wouldn't boot for me after post-installation patches. Perhaps you can give that a shot but I guess it depends on the current state of your dGPU. I have it disabled via NVRAM because it's defective. I can't confirm whether sleep is working or not though because I'm still in the process of testing it but at least I know that brightness control is now working for me.

**Comment by vicman777** [comment]
Tried using OCLP 0.1.5 with the same result, but thanks for the idea. Do you know how I can see the startup logs from recovery/terminal so I can see what it is stalling on?

**Comment by guanzhangrtk** [comment]
Just to clarify, you re-installed Big Sur latest version, installed OCLP 0.1.5, it boots but after applying post-install patches it doesn't boot any more? What is the condition of your dGPU? Is it functioning or did you also have it disabled in NVRAM?

I don't know how to get the startup logs because even if I enable verbose booting it would end up being stuck with the Apple logo with empty loading bar, but an idea is to boot completely from single user mode but I don't know exactly how to do that, perhaps you can try Googling.

**Comment by khronokernel** [comment]
Likely hardware fault, recommend discussing further on forums such as MacRumors
