### ISSUE TITLE
[Bug]: Screen freeze on reboot after applying Post Install patch 

### ISSUE THREAD

**Issue by griftopia** [dortania/OpenCore-Legacy-Patcher#473]
### Machine Model

iMac11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

After applying Post install Patch *but* before copying EFI folder, during the reboot to test graphics acceleration works, boots to login screen and then freezes with tiny squares all over the splash screen. Cannot type in password or anything. Just frozen. Have already replaced hard drive in case that was the issue. Tried many times. Same problem.

![39D92E53-A90A-46B4-BB9E-52178115E630](https://user-images.githubusercontent.com/90117556/132110778-a1104666-da4a-414e-bc8b-37f0f0506557.JPG)

### Any Additional Information

Exact Model
https://everymac.com/systems/apple/imac/specs/imac-core-i5-2.66-27-inch-aluminum-late-2009-specs.html

Sometimes if I'm quick, I can login, and then screen freezes.

**Comment by khronokernel** [comment]
Looks like the GPU's on the verge of dying, very common symptom are screen artifacts such as those. Recommend upgrading the GPU to a newer Metal card so no post install patches would be needed:

* https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/?post=17425857#post-17425857

Big Sur overall is much more taxing on older hardware especially after installation, which may be why this issue is not as noticeable on native OSes such as High Sierra. For further troubleshooting, forums would be the recommended space
