### ISSUE TITLE
MacBookPro11,3 GMUX issues with 12.0 Beta 7 and newer

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#522]
With macOS 12.0 Beta 7, Apple had removed Nvidia Kepler acceleration. Because of this, we are required to root patch acceleration back in. (implemented with v0.2.5)

However with MacBookPro11,3 machines, their GMUX defaults to the dGPU in UEFI and on inital OS loading. After the graphics stack loads in, GMUX will pass control over to the iGPU.

However since Kepler drivers are missing in Beta 7, the GMUX fails to transfer Display ownership over to the iGPU. This results in a black screen for the user as the dPU is dead and the iGPU is not hooked up.

## Work Around

To resolve, users must either disable the dGPU or boot via Safe Mode.

For us, there's nothing we can do besides notify the user in our documentation to use Safe Mode to boot into the OS to root patch:

* [ ] Update Documentation to reflect GMUX issue and work-arounds

# References

* To trigger Safe Mode from OpenCore's Picker:
  * Press `Shift`+`Enter` on the macOS entry
* To disable the dGPU for UEFI:
  * `sudo nvram FA4CE28D-B62F-4C99-9CC3-6815686E30F9:gpu-power-prefs=%01%00%00%00`
  * Arg can be set to `%00%00%00%00` when user has root patched Kepler support back in

**Comment by sunyinqi0508** [comment]
Hi, I'm still getting black screens on beta 8 after patching with 0.2.5. The black screen happens shortly after I logged in to the desktop and the dGPU seems to be down no matter if I disabled it or not. Removing Lilu from EFI doesn't help either. However there's no problem in Safe Mode.

**Comment by hxlph** [comment]
is this still the case? After an install, I will have an Apple logo screen permanently on display, even though I can hear Siri talking on the setup screen.

**Comment by vdm-alt** [comment]
It is not necessary to transfer the computer to UMA, you can go through the initial installation by booting the computer with the shift key pressed on the right side, apply the patches and then restart normally. In general, we can say that there is no point in installing Monterey on MBP11.x. It loads every other time, you have to go back to Big Sur.

**Comment by vdm-alt** [comment]
<img width="883" alt="Снимок экрана 2021-12-11 в 09 23 03" src="https://user-images.githubusercontent.com/83856941/145660713-a7b1e6d8-7d2a-44d9-b809-aa6bbec39f43.png">

This NVMeFix.kext causes kernel panic intermittently. It does not need to be enabled for MBP 11.x models.

**Comment by vdm-alt** [comment]
It depends on the condition of the equipment. Only the line "fa4ce28d ..." may not be enough, the "nv_disable = 1" flag may be required. Of course, it's easier to go through the initial setup in a safe mode.

**Comment by satmandu** [comment]
@vdm-alt What is the best way to disable NVMeFix?

**Comment by P0cket-Sevens** [comment]
> Hi,
> 
> I would like to report that from my experience, the suggested Safe Mode workaround works fine **only** with upgrades and installations from scratch.
> 
> However, I've been **unsuccessful in restoring** from a Time Machine backup using the Migration Assistant. 
<snip>
> All this to say that only the temporary Nvidia deactivation seems to be a **safe & universal workaround**. Also the nvram command does seem to do the trick. I've been running the following script in a live linux session successfully though: https://github.com/0xbb/gpu-switch
> 
> I hope this feedback can save people a few headaches & time.

I've run into the same issue trying to restore via Time Machine.  If I try to do a normal boot after restoring, the Mac won't boot.  Booting into Safe Mode keeps showing the "migration complete..." message.  Were you able to get around this issue?  If so, I'd be curious to know how you did.  Thanks in advance.

**Comment by vdm-alt** [comment]
> What is the best way to disable NVMeFix?
You can disable it by choosing "no", you can completely delete the line associated with it completely. The new version 0.3.3 does not install it anymore.
![Снимок экрана 2021-12-17 в 09 06 28](https://user-images.githubusercontent.com/83856941/146477541-eb5a1aaa-629d-4679-a511-b4e366687fdd.png)

**Comment by P0cket-Sevens** [comment]
@vdm-alt Thanks for the reply.  I'm now going to ask a dumb question: what program are you using to set this value?  Thanks.

**Comment by vdm-alt** [comment]
plistedit pro for mac

**Comment by vdm-alt** [comment]
I don't see such a problem, sorry. Just checked it out. OCLP 0.3.3 Monterey 12.1
<img width="508" alt="Screenshot 2021-12-17 at 14 10 58" src="https://user-images.githubusercontent.com/83856941/146504683-114b717e-cb43-4d33-a20b-4c99fa0b6142.png">

**Comment by svemonix** [comment]
> I've run into the same issue trying to restore via Time Machine. If I try to do a normal boot after restoring, the Mac won't boot. Booting into Safe Mode keeps showing the "migration complete..." message. Were you able to get around this issue? If so, I'd be curious to know how you did. Thanks in advance.

I did what you quoted. I boot linux from a live USB drive. Ubuntu here may be best because Broadcom wifi can be turned on easily with the "additional drivers" app. Then I download the script above and execute it as root to force the iGPU in macOS. Form there the installation process will go as smoothly as if you had no Nvidia card.

Now, I follow the same process for all updates. The safe boot trick did not work for me with the upgrade to 12.1. Also, it's pretty cumbersome to watch out for reboots anyways. Interestingly, the Nvidia card got reactivated automatically after the upgrade to 12.1 was complete. Previously, I needed to return to Linux to reactivate it with the same script.

**Comment by jyounus** [comment]
Hi, a complete noob here who's going to try and install Monterey on his MacBookPro11,3 for the very first time. 
Can someone tell me if it's a good idea to upgrade to 12.1, or not? I'm not sure I understand @vdm-alt's comment. The OCLP's docs has 11,3 listed as fully supported. Thanks in advance.

> **In general, we can say that there is no point in installing Monterey on MBP11.x**. It loads every other time, you have to go back to Big Sur.

**Comment by thi-baut** [comment]
> 

It's probably not worth it if you have a dual GPU (discrete GT 750M), lack of native compatibility and issues arising from that

**Comment by satmandu** [comment]
My MacBookPro11,3 system was unstable on 12.1 until I installed [mac fan control](https://crystalidea.com/macs-fan-control) and set the fans to turn on with the following settings:
`Left side` fan set based upon `Sensor-based value` of `CPU Core (average)` to start the fan at 55C, with a max temp 70C
`Right side` fan set based upon `Sensor-based value` of `GPU` to start the fan at 55C, with a max temp 68C

I also put down some new thermal compound on my CPU and GPU, since this is a seven year old machine.

It hasn't crashed since I made those changes, so I guess that's good?

**Comment by vdm-alt** [comment]
If GT750 M is not stable and does not withstand the load, you can use a program switch gfxCarsStatus or gSwitch. In general, I no longer see problems with the stability of 11.x in Monterey. 12.1 only took longer to load.

**Comment by satmandu** [comment]
Ironically gpu instability was an issue with my 15" 2010 MBP, which required a hardware repair, before which I was using those sorts of apps to manually force the dGPU to be disabled.

As I recall, the Intel GPU is painfully underpowered for running programs like Google Chrome, so if the fans blasting keeps the GPU stable enough not to crash the machine, I'm all for it.

**Comment by vdm-alt** [comment]
Intel Iris Pro has a very impressive and sufficient performance. You can even play on it.
<img width="401" alt="1" src="https://user-images.githubusercontent.com/83856941/147437333-0ce1b679-004e-4072-b1c3-9b65d6ef53d9.png">
A discrete video accelerator is useful if you are using an external monitor or projector because it always loads the discrete video card and this will allow two desktops with different resolutions to be used rather than a clone of the desktop.
In addition, this is still a laptop, you don't want to hear the constant whine of fans from it.
![11 2](https://user-images.githubusercontent.com/83856941/147437361-c3ab8e10-09c8-445a-9f84-40762fa92ef4.png)
<img width="780" alt="11 3" src="https://user-images.githubusercontent.com/83856941/147437374-75987215-a82f-49d8-aa4a-6c375053d989.png">
However, all that has been said is exclusively my personal opinion and I do not impose this on anyone.
