### ISSUE TITLE
FeatureUnlock causing extreme slowdowns and halts

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#564]
As reported and tested with Monkiey#3060 on Discord, it's been found that FeatureUnlock can create OS instability for some users even in short periods of time. 

There is potentially a link between low GB/aged RAM with this issue, however no concrete link can be determined at this time.

### Symptoms

* OS will suddenly slow down
* Applications will start to crash
* Applications cannot be restarted

### Work Arounds

The only solution currently to mitigate this issue is to run `sudo purge` via ssh from another machine. Additionally simply disabling FeatureUnlock with `-caroff` boot-arg is another option. Unfotunately this does now remove many of FeatureUnlock's benefits such as Airplay to Mac, NightShift, etc

### Additonal Notes

Currently this issue cannot be replicated at all locally with any machine on hand. In additon to this, we have no reliable logs on ram usage, processes running, etc at the time of these crashes. Determining a solution will be quite difficult

Additionally I've made a stripped down variant that only patches nightshift or Sidecar:

* [FeatureUnlock-1.0.4-NightShift.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7339727/FeatureUnlock-1.0.4-NightShift.zip)
  * [nightshift-diff.patch.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7339750/nightshift-diff.patch.zip)
* [FeatureUnlock-1.0.4-Sidecar.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7339761/FeatureUnlock-1.0.4-Sidecar.zip)
  * [sidecar-diff.patch.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7339763/sidecar-diff.patch.zip)

Tests appreciated to see where our issue might lie

**Comment by ripley80** [comment]
I added -caroff to the NVRAM section of config.plist and rebooted. I hope this is the right way to disable FeatureUnlock. I will now see if there are still some crashes of mostly background processes like daemons. The situation has improved a lot by updating Big Sur to Monterey Beta 9 though.

**Comment by Marty56** [comment]
I am experiencing this on a MacBookAir 4,2 using OCLP 3.1

**Comment by wlwong703** [comment]
Having the same issue with Mac Pro 4,1 -> 5,1, OCLP 0.3.1 and macOS 11.6

**Comment by franetic** [comment]
I too experienced this (OCLP 0.3.1) after updating Big Sur 11.6 to 11.6.1 on an iMac11,2 with upgraded WiFi/BT (BCM943602CS) and upgraded GPU (AMD WX4150). A few minutes after logging in applications would start crashing and I wasn't able to restart them. Menu bar was barely responsive. I wasn't able to determine the trigger for that behaviour. 

I decided to upgrade to Monterey 12.0.1 to see if the issue persists. I simply downloaded the installer via System preferences and ran it from Applications. After a few minutes it would report an error and suggest to 'run the installer again'. After a few reboots and unsuccessful installation attempts I decided to disable FeatureUnlock.kext in OC config.plist. After that the Monterey installation proceeded without a problem. I have then reenabled FeatureUnlock.kext and the issue seems to be gone (for now).

**Comment by ripley80** [comment]
With --caroff boot arg I have zero problems on my 12.0.1 MacBookPro9,1.

mm@MacBookPro ~ % uptime
 9:58  up 7 days, 19:56, 5 users, load averages: 3,01 2,87 2,63

I will keep it like this for a few more days and then remove --caroff to see if it makes a difference.

**Comment by lor1x** [comment]
Using -caroff in config.plist solves the issue on MacBookAir6,1 with Monterey 12.0.1

I switched it off and used the SideCar patch provided but the issue resurfaced. As soon as this pops up everything starts to crash when using keyboard shortcuts or right clicking in certain places (mostly Finder, anywhere on it or folders/files)
![Screen Shot 2021-10-29 at 12 24 50 AM](https://user-images.githubusercontent.com/22913459/140523109-eb1855e9-6aa0-4b27-a914-5f3b95cf6d12.png)

**Comment by VinylNerd** [comment]
it seems me and a bunch of people using my EFI linked above by @SinaGamer55 have been experiencing similar issues, have been using feature unlock since it was released and have not been able to explain this, if you check the thread linked above by @SinaGamer55 you can see he linked to what seems to be the newest version of FeatureUnlock 1.0.4

personally i have updated my build to this 1.0.4 version, i will give it a go, and if i get a crash ill be removing the kext from the build to see if i can solve the issue like everyone else by simply removing/disabling FeatureUnlock

i dont believe i need this kext but i will have to check, i believe i only need it for sidecar and i dont own an ipad, i think airplay works for me without it since i have a genuine apple wifi card

cheers all, will report back with more info when i have it.

**Comment by thecoder-001** [comment]
Hi!
Looks like macOS 12.1 has reintroduced the issue on my MacBookAir6,2 (OCLP 3.3).
Without -caroff, the crashes have been pretty frequent and either throw me back to the login screen or result in the issues described in the parent comment (general slowing down, applications no opening/misbehaving, brightness-fn keys not working/working after long delay). A `sudo purge` seems to recover from the condition as suggested.

![Screenshot 2021-12-19 at 9 28 14 AM](https://user-images.githubusercontent.com/25097841/146663372-faefe011-f1d7-414d-9c86-15c768802fb9.png)

After adding `-caroff` to my boot ages there haven't been any crashes or slowdowns and my Mac has managed an uptime of about two days. Console also doesn't shows any crash logs.
Requesting to reopen the issue. Cheers.

**Comment by hearnia2k** [comment]
@thecoder-001 would you be kind enough to help me understand how to add the boot-args?  I tried looking, but didn't find much info, and feel like I'm missing something super obvious!

Of course, this also means I am still getting the issue here.  I am on a MacbookPro11,2, running 12.0.1.

Thanks!

**Comment by thecoder-001** [comment]
Hi @hearnia2k . 
You need to mount the efi partition (the docs seem to recommend [MountEFI](https://github.com/corpnewt/MountEFI) for that, but for me just using ` sudo mount` worked too). 
Then go to the mounted EFI folder > EFI > OC > config.plist. Open up the file and search for "boot-args". 
Then add `-caroff` inside the <string> tags along with your pre-existing arguments (for eg, here's how mine looks after editing `<string>-caroff keepsyms=1 debug=0x100</string>`).
Hope this helps.
Cheers

**Comment by Minims** [comment]
Same issue here on MacBookAir6,2 with last OCLP. Can we reopen this issue ?

**Comment by khronokernel** [comment]
0.3.4 allows user configuration for FeatureUnlock in TUI as a work-around for the time being.
Seeing as we still cannot replicate this issue locally with any of our developers, it's difficult for us to gauge the scope of the issue and even more challenging to try and resolve it.

Regarding reopening the issue, we only do this for issues we plan on resolving. Adding configuration would be considered "resolved" from our perspective

**Comment by Minims** [comment]
I have disable FeatureUnlock for now with last dev build. Checking if it works.

Is there any info/help I can provide to debug this ? 

I'm not sure but I think the issue happens when the macOs disk has FileVault activated on the internal drive. I have a second Monterey install on an external USB SSD (with same MacbookAir6,2) without Vault, and I have not seen the issue for now on this one.
