### ISSUE TITLE
[Bug]: No internal USB2 support

### ISSUE THREAD

**Issue by galluslongus** [dortania/OpenCore-Legacy-Patcher#577]
### Machine Model

MacPro4,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

After running ocLP 0.3.0 i dont have any mouse or keyboard on my MacPro4,1 patched to 5,1 running BigSur11.6
I have a USB3 Card installed where mouse and keyboard are detected and running fine.
So, comming from ocLP 0.25 and OC 0.74

After Standby i cant wakeup with mouse or keyboard connected to USB3 PCI Card, have to go to internal USB2 port, hit a button and go back to USB3 Port.

**Comment by khronokernel** [comment]
Cannot be replicated locally with a MacPro4,1 flashed to 5,1, are you certain the USB 2.0 ports are broken? It might be the Big Sur/Monterey USB 1.1 issue some face. Try plugging a USB 2.0 hub between the mouse and keyboard

This issue is fairly common between MacPro3,1-5,1, no fix is really known. The issue also common occurs randomly and can stay for some period of time. The USB 2.0 hub method is the only reliable solution as this forces the EHCI controller to be active over the flaky UHCI
