### ISSUE TITLE
Fix for BigSur dualGPUs blank screen

### ISSUE THREAD

**Issue by jacklukem** [dortania/Opencore-Legacy-Patcher#6]
Hello @khronokernel, since through your OC Legacy Patcher for enabling OTA updates you are spoofing to `iMac15,1` that is an Haswell architecture BigSur supported Mac, for fixing dualGPUs blank screen (after the apple stage2 loading bar) you might need the [pikeralpha's AppleGraphicsDevicePolicy fix](https://pikeralpha.wordpress.com/2015/11/23/patching-applegraphicsdevicepolicy-kext/) that is adding in OC config.plist boot-args: `agdpmod=pikera`

I also advise to add `-no_compat_check` because even if you spoof a supported board id, in some circumstances this is ignored using anyway the stock BigSur PlatformSupport.plist that of course doesn't contain the unsupported legacy Mac board id.

My example on how I'd modify the AppleNVRAM key:

```javascript
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>boot-args</key>
				<string>keepsyms=1 debug=0x100 -no_compat_check agdpmod=pikera</string>
```

**Comment by khronokernel** [comment]
Oh thank you for notifying about the AGDP issue, I assumed WhateverGreen would handle this by itself but I can add it shortly. I believe that might actually be the issue listed [here](https://github.com/dortania/Opencore-Legacy-Patcher/issues/3)

Regarding usage of `-no_compat_check`, I feel this is ideal to have users always boot OpenCore as we include many of the patches. Its much easier to notice you're not booting OpenCore when you hit the initial boot wall instead of boot into the OS and see many things break

I'll close this issue once I've added the AGDP patch into the patcher
