### ISSUE TITLE
BootCamp MBP9,2 does not recognise sound card - Windows 10

### ISSUE THREAD

**Issue by CuchoM** [dortania/Opencore-Legacy-Patcher#67]
I've installed BootCamp WIN10 and does not recognise sound card from MBP9,2 to -> OCLP MBP11,1, How to solve this issue?

**Comment by khronokernel** [comment]
Did you run BootCamp's installation software before or after running OCLP?

**Comment by CuchoM** [comment]
I've run after OCLP a clean install of WIN10 using bootcamp but audio didn't work . I don't know how to solve it

**Comment by CuchoM** [comment]
At macOS BS works really perfectly, the most impressive work to run at unsupported machines, just the sound card at windows that really I don't know how to solve due to my beginner initiation  at OC

**Comment by khronokernel** [comment]
Latest OCLP release should resolve this with the new SMBIOS system, you have 2 options:

- Re-install the bootcamp utilities without OpenCore booted
- Install the new OpenCore Patcher and try again

Note: We do not recommend running the BootCamp utility in macOS on an unsupported Mac with OpenCore. This is due to Apple's logic with older hardware clashing with what it thinks it's running on. No risk of bricking, but more likely a headache. Will update the README.md regarding this
