### ISSUE TITLE
[Bug]: MacBook Pro 13 early , SD card SDXC time out 

### ISSUE THREAD

**Issue by WikiHacker** [dortania/OpenCore-Legacy-Patcher#673]
### Machine Model

MacBookPro10,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

System boot up takes 5-10 minutes 
![3F23E013-40D0-4961-B21C-B21C972830F9](https://user-images.githubusercontent.com/2268341/139570071-1da1dec7-6276-4ab5-b817-09108fbb2829.jpeg)
![6023F217-8B86-4030-9160-2517B3813B95](https://user-images.githubusercontent.com/2268341/139570081-5bfb89e0-89d1-4ec4-a342-91e619b06e05.jpeg)
![CAEA09B9-5DB5-4781-8188-E47E9B16B8C9](https://user-images.githubusercontent.com/2268341/139570084-a51c0231-62e8-4c9a-b9ea-4cbad9732b12.jpeg)
![081A171C-A4AE-4FA3-8C18-F4CA706921C2](https://user-images.githubusercontent.com/2268341/139570087-39253a47-0266-4b63-8134-94b1063db113.jpeg)

**Comment by khronokernel** [comment]
If the issue is non-replicable without that SD Card, sounds like a hardware fault/driver fault with macOS. Your system is equipped with a `pci14e4,16bc` PCIe based SD card reader. The newest system to ship with this exact controller is iMac18,3 (2017 27" 5k iMac) thus making this a macOS issue that Apple needs to resolve

If you're able to find a work around to this on your end, feel free to submit a patch set and we'd be grateful to integrate into the project
