### ISSUE TITLE
[Bug]: Weird Google Street View page crash under Big Sur (possibly Metal-related?)

### ISSUE THREAD

**Issue by sergioag** [dortania/OpenCore-Legacy-Patcher#681]
### Machine Model

MacBookPro9,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

(please read fully - it may initially look as a 3rd party app issue, but the rationale for thinking it may be OpenCore Legacy-related follows)

Steps to reproduce:
1. Go to https://maps.google.com
2. Select any point in any major city that has StreetView available
3. Click on the Street view icon
4. Page crashes

Expected behavior:
Be able to see the street and move around.

Reproducible under both Chrome 95 and Safari 15.1 under Big Sur.

Under Chrome, it works with "Use hardware acceleration when available" disabled, albeit very slowly.

Tested in a MacBookPro9,1. Was working under Catalina just before the update.Nothing else was changed except upgrading to Big Sur with OpenCore Legacy.

Also tested with a MacBookPro15,3 running same versions and everything worked fine (with "Use hardware acceleration when available enabled).

More details on the test machine:
- File Vault it enabled
- SIP is enabled
- Filesystem is case-sensitive
- 16GB of RAM
- OWC SATA SSD
- Has Intel HD4000 + NVidia GeForce GT 650M
- macOS BigSur 11.6.1
- No other issues

**Comment by sergioag** [comment]
I found this in dmesg when the issue happens in Chrome:

```[27607.134055]: void IOAccelContext2::setContextError(uint32_t): stream error found.  token_id was 0x9800 token_size was 0x0008
[27607.134111]: The graphics driver has encountered internal error 0x0, 0xfffffffb.
[27607.134191]: AMFI: Denying core dump for pid 714 (Google Chrome He)AGC:: [Google Chrome He pid 714 mux-aware] exiting, non-mux-aware app count 0, runtime: 7:19:22.704
```

**Comment by danielbui78** [comment]
I can confirm that my recent install of Big Sur + OpenCore-Legacy on MacbookAir5,2 has similar crash.  It did previously work in Catalina... until the recent Catalina Security Update 2021-007 (released Oct 25). 

Since the Security Update 2021-007 was released, many people are reporting OpenGL based apps are crashing on Macs using HD4000 graphics.  It appears this security update contains several changes to the Intel graphics drivers.

Here is a link to a thread which details a similar test using Google Streetmaps as the original post:
https://www.mactechnews.de/forum/discussion/Grafiktreiber-fuer-Intel-HD-Graphics-4000-nach-Sicherheitsupdate-2021-007-fuer-macOS-Catalina-defekt-345313.html
[English Translation: https://www-mactechnews-de.translate.goog/forum/discussion/Grafiktreiber-fuer-Intel-HD-Graphics-4000-nach-Sicherheitsupdate-2021-007-fuer-macOS-Catalina-defekt-345313.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=nui,sc]

I restored Catalina backup prior to security update and confirmed that installing the update causes the crash behavior.  I ran glView before and after the updates and found that the Intel OpenGL version is changed in the update:
Prior to Security Update, glView reports: Intel HD Graphics 4000 OpenGL Engine, OpenGL version 4.1 INTEL-14.7.8
After Security Update: Intel HD Graphics 4000 OpenGL Engine, OpenGL version 4.1 INTEL-16.5.4

Is there a way to install the previous Intel HD4000 OpenGL driver in Catalina and Big Sur?  If possible, this would confirm that the Security Fixes made by Intel are likely the cause of these crashes.

**Comment by danielbui78** [comment]
Confirming that installing Big Sur 11.4 + OpenCore-Legacy-Pacther 0.3.1 on MacBookAir 5,2 (HD4000) fully works without crashes in Google Streets or any other OpenGL application.  

I'm out of bandwidth for the month, so can't download updates to do further testing to systematically prove that 11.6.1 is the cause of the OpenGL/HD4000 crashes.  However, once proven, I think this Bug report should be changed into a feature request since Apple may have effectively removed its undocumented support for HD4000 in Big Sur.

**Comment by khronokernel** [comment]
Seeing as this is an Apple issue, we're unable to dedicate time to working on this as OpenGL support is further stripped from the OS. Additionally in Big Sur we do not touch the graphics stack at all on HD4000, only with Monterey so fixing this issue would require extensive research and perhaps adding root volume patching to Big Sur (which is not ideal from a patcher perspective, as we're adding an extra failure point)

However we'd be more than happy for others to help contribute to the project!

**Comment by Ausdauersportler** [comment]
https://communities.apple.com/de/thread/253320172?answerId=256216326622&cid=em-com-apple_watches_email_thread_owner-view_the_full_discussion-de-de-11192020&page=1
