### ISSUE TITLE
[Bug]: Activating FileVault2 on macOS 11.6(.1) renders system unbootable

### ISSUE THREAD

**Issue by HackintoshHD** [dortania/OpenCore-Legacy-Patcher#709]
### Machine Model

MacBookPro5,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

According to the [OpenCore Legacy Patcher 0.2.5 changelog](https://github.com/dortania/OpenCore-Legacy-Patcher/releases/tag/0.2.5), it has become possible to activate FileVault 2 on Root Volume Patched Systems - quote:

> Allow Root Volume Patched Systems to use FileVault 2
> 
> Requires macOS 11.3 (20E232) or newer

I've therefore tried activating FileVault 2 on both macOS 11.6, 11.6.1 Big Sur and macOS 12.0.1 Monterey which were installed and root volume-patched using OCLP 0.3.2 TUI nightly: While the encryption process for the system's data volume seems to be completed successfully, the respective OS is unable to boot on the first following attempt to reboot and I'm being displayed a 'support.apple.com/mac/startup' screen. So just to be sure: Is the FileVault 2 entry for OCLP 0.2.5 above intentional or is it maybe some sort of editorial error? - Thank you.

**Comment by khronokernel** [comment]
We'd done some pretty rigerous testing on stock Macs to ensure FileVault is reliable and safe. We've tested on the following models:

* MacBook5,1
* MacBook7,1
* MacBookPro8,2
* MacBookPro9,2
* iMac8,1
* MacPro3,1
* MacPro5,1

However one of our devs, EduCovas, had issues with their iMac8,1. The only difference between their machine and our testing suite is that his has the APFS mod patch while all our machines are running stock Apple firmwares. Assuming this is the issue, reverting to a stock firmware should resolve this issue. Otherwise you'd be best to troubleshoot on forums

Will add a note to the guide regarding FileVault on non-stock firmwares

**Comment by HackintoshHD** [comment]
@khronokernel Thank you so much, that hint was spot-on! After reflashing my MacBook Pro's ROM with the untouched ROM's backup dump, I can happily confirm FileVault 2 is now functional on my 17" MacBook Pro Mid 2009 with macOS 11.6.1 Big Sur. So if that test is enough, the following model could be added to the list:

- MacBookPro5,2

**Comment by HackintoshHD** [comment]
[Documentation](https://forums.macrumors.com/threads/macos-12-monterey-on-unsupported-macs-thread.2299557/page-119?post=30588392#post-30588392) on macrumors.com.
