### ISSUE TITLE
Graphics On Boot low Res

### ISSUE THREAD

**Issue by rushin92** [dortania/OpenCore-Legacy-Patcher#715]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true, false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

Lock Screen Gets 0.1% More Pixelated it is super noticeable This Was Done on A 2016 13,1 MacBook Pro for airplay to mac to Get Unlocked Fixed After Loging In But After A Restart Happens Till Login/Unlock

**Comment by khronokernel** [comment]
> Lock Screen Gets 0.1% More Pixelated

Is this an OCLP bug or just Monterey? I'm unfortunately unable to really understand the issue especially if login resolves it. As we have no native Intel Macs on hand, we're unable to really debug further on our end. No HiDPI Macs we support have reported this exact issue, however all our test systems are pre-2016.

Feel free to research further and PR if you know the cause, otherwise we're unable to dedicate resources into investigating at this time
