### ISSUE TITLE
WIFI password window on MacPro 3,1

### ISSUE THREAD

**Issue by Ivantroniks** [dortania/OpenCore-Legacy-Patcher#792]
### Machine Model

MacPro3,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Hi

WIFI password window does not appear in MacPro 3.1 in Monterey annex IORegistryExplorer output...

[MacPro3,1.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7700510/MacPro3.1.zip)

(IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP04@1C,3/IOPP/ARPT@0/AirPort_Brcm4331)

I found this information that comments on educovas "Password window is already fixed on 0.3.2 nightly"; apparently on my WIFI card to not be solved instead on my iMac 8.1 if it has been solved ...

Thanks.

**Comment by khronokernel** [comment]
The password window fix is only applicable for non-Metal due to reliance on SkylightPlugin system. As your system has socketed wireless, upgrade the hardware to a native module

Closing as will not fix, however feel free to develop your own patch set that doesn't rely on the SkylightPlugin system on non-Metal. Always appreciate more help
