### ISSUE TITLE
Two terminal windows close on quit (TUI patcher)

### ISSUE THREAD

**Issue by mallardtheduck** [dortania/OpenCore-Legacy-Patcher#803]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

When the TUI patcher application quits, it closes the previously-used terminal window (if there is one) in addition to its own window. This can be rather annoying when you have work in that window...

**Steps to reproduce:**

1. Launch Terminal.app (this opens one terminal window)
2. Launch OpenCore-Patcher.app (this opens a second terminal window)
3. Quit (Q) as soon as the menu loads

Note that _both_ terminal windows are closed, not just the one that OpenCore-Patcher.app created. (If further terminal windows are opened, they are left alone, so it's not just quitting Terminal.app). Thankfully, if Terminal.app detects that a program other than the shell is running, it will display the "Do you want to terminate running processes in this window?" message giving the user a chance to save their work.

**Expected behaviour:**

Quitting OpenCore should only close the terminal window that it created.

**Comment by khronokernel** [comment]
This is most likely a byproduct of how [PyInstaller](https://www.pyinstaller.org) works with TUI applications, as it calls Terminal and launches its instance afterwards.

You can run the [source variant](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/SOURCE.md) with python3 as a work around, however we actually cannot replicate this behaviour based off your "Steps to reproduce:" you provided above.

Seeing as this issue is most likely not with our source but instead PyInstaller's and we cannot replicate locally, I would recommend researching yourself further and potentially submitting a PR. We always greatly appreciate any additional help with the project
