### ISSUE TITLE
Extremely Long Boot Time Macmini 6,2 2012

### ISSUE THREAD

**Issue by ingsocdev** [dortania/OpenCore-Legacy-Patcher#809]
### Machine Model

Macmini6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

It takes over 10 minutes to boot up Monterey. I upgraded to Monerey from an install that I created via the deprecated Big Sur Micropatcher guide. Is there anything I can do to improve the boot up time? Once botted up, the OS seems to perform roughly the same as Big Sur before it.

**Comment by khronokernel** [comment]
Without proper logs, verbose, etc, difficult for us to debug. Use forums to troubleshoot further, ideally keep issues tab to more formulated issues

Small suggestion: boot with as few non-essential devices plugged in. Generally USB and SD cards can sometimes cause the system to hang due to unknown/bad hardware state
