### ISSUE TITLE
iMac 14,3: alert system sound greyed out (and system sound effects not available)

### ISSUE THREAD

**Issue by mat1696** [dortania/OpenCore-Legacy-Patcher#830]
### Machine Model

iMac14,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

With the latest version of OCLP (and macOS build 21D5025f, didn't test with earlier build) the sound effect pane of System Preferences is completely greyed out (see screenshot). Consequently no system sound effect is played, except the volume modification one (and maybe a few other I haven't noticed yet), but sound like emptying the trash, screenshot, deleting a file, etc are not played.

It is NOT an issue with my macOS version/install, as I tried unpatching it and then booting on a supported MacBook Air and these sound effects work as expected. Please tell me what I can do to help with this issue.
![SysPref_ISSUE](https://user-images.githubusercontent.com/86326794/146901631-09b533a6-4b0b-4662-beb9-a6cbf964e53b.png)

**Comment by khronokernel** [comment]
21D5025f is a brand new beta, filing against an Apple beta without verifying this bug on a properly supported build of Monterey makes it quite difficult for us to determine the root cause of the issue.

Regardless we do not touch the audio stack on iMac14,x, and looking at AppleHDA between 12.0.1 and 12.2 there are no dropped layout IDs which would warrant a concern of dropped hardware support on our end.

> It is NOT an issue with my macOS version

This is not valid debugging when you're testing across different hardware families. Additionally this is still a developer beta build, tests should've been conducted on a release build.

Best to troubleshoot further on forums, as we have no reason to believe this is a legitimate bug with OCLP and thus cannot realistically invest development time into researching your system specific issue.
