### ISSUE TITLE
File date does not match v0.3.3

### ISSUE THREAD

**Issue by sslupsky** [dortania/OpenCore-Legacy-Patcher#832]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Downloaded GUI version 0.3.3 from the Releases page.  The "File Created" and "File Modified" dates reported by Finder are both Oct 4, 2021 which is not the same date as the release date on the website.  The version reported by Finder is 0.3.3.
<img width="1032" alt="Screen Shot 2021-12-21 at 8 23 08 AM" src="https://user-images.githubusercontent.com/16888734/146954954-f6f878ec-4c52-4ceb-a940-b4f06d24f272.png">

Not sure if this is just an anomaly or an indication of a compromised download.

**Comment by sslupsky** [comment]
As noted in the screenshot above, the TUI version appears to have the correct date associated with it.

**Comment by khronokernel** [comment]
This is due to how the build system generates the GUI:
* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/.github/workflows/build-gui.yml

As you can see, our GUI is pulled from another repository which the last commit was October 4th:
* https://github.com/dortania/OCLP-GUI

Build system pulls the GUI, merges the updated CLI tool and pushes binary to release

We will be deprecating the old GUI for a new wxPython based variant which would be built every commit along side the TUI so date would be reflected more accurately. However for the time being, refer to the application's version as it will report what version it is (ie. 0.3.3)
