### ISSUE TITLE
I can't open the tui version of the patcher.

### ISSUE THREAD

**Issue by MultimediaLucario** [dortania/OpenCore-Legacy-Patcher#870]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I'm currently trying to run macOS Monterey on my ThinkPad T440S through an external drive for testing and I am trying to use the OC Legacy Patcher. However, the terminal will not open the TUI version of the OpenCore Legacy Patcher.

**Comment by Thyssenkrupp234** [comment]
First of all, OpenCore Legacy Patcher is meant for actual unsupported macs, and is not used for hackintosh. See https://dortania.github.io for a guide. Try running the actual executable file into the terminal and see if that launches

**Comment by khronokernel** [comment]
If you're running from source, ensure your dependancies are correct:
* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/SOURCE.md

If this is the prebuilt bundle, there should be no issue with the current release binaries.

If your system is slower, please wait about 15-30s for the TUI to start. PyInstaller's `--onefile` option we use on our binaries can create extended launch time on first launch as macOS expands and caches our resources. Generally this is 5s but can be more.

Otherwise as Thyssenkrupp234, you'd be best to try manually launching the binary and research your issue further online
