### ISSUE TITLE
Screen Brightness Keys not working (Cannot adjust brightness after Big Sur + update )

### ISSUE THREAD

**Issue by DannMendis** [dortania/OpenCore-Legacy-Patcher#900]
### Machine Model

MacBookPro11,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Please clearly explain the issue

For some reason the brightness keys not working, I was wondering if this related to below, in this case any luck of getting a feature in the settings to enable the brightness keys. This stupid apple blocking everything to make people pay and money hungry F%^$#s.

Cannot adjust brightness after Big Sur update:
https://developer.apple.com/forums/thread/675936?answerId=680954022#680954022

**Comment by khronokernel** [comment]
For MacBookPro11,1, we're relying on the native Haswell graphics stack. MacBookPro11,4 is a Haswell iGPU only model similar to the 11,1, so drivers should still function so long as that model is natively supported.

You'd best validate Big Sur functions correctly as that forum discussed, as well as test a fresh Monterey installation. Otherwise troubleshoot on forums
