### ISSUE TITLE
Kernel panic when connecting ethernet cable on Thunderbolt Elgato Dock iMac12,2

### ISSUE THREAD

**Issue by campodit** [dortania/OpenCore-Legacy-Patcher#939]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

Kernel panic when connecting ethernet cable on Thunderbolt Elgato Dock iMac12,2

[https://drive.google.com/file/d/1fbDGHkjq4jk8kZQAAMhpev3BLmlagXCX/view?usp=sharing](url)

### What steps have you taken to troubleshoot this?

Graphic card : WX7100

Also tested on iMac12,2 with K610M graphics card under Big Sur -> same problem

This makes my router crash, which I have to reboot. We can see the DHCP addressing on the wifi does not work anymore on the video 

No problem found with MacBookPro11,1 on Monterey with OCLP, ethernet recognized / no kernel panic

Also, I had to add agdpmod=pikera in boot-args so that the external screen works through the dock (for the iMac with AMD)

**Comment by khronokernel** [comment]
Quite a strange issue I must say, this may related to the lack of VT-D support on pre-Ivy bridge models. Potentially similar situation to the BCM5701 changes in Big Sur I documented:

* [Big Sur and legacy Mac support: Networking](https://khronokernel.github.io/macos/2021/08/15/OCLP-NETWORK.html)

However because the i210 driver lives in userspace via DriverKit, I'm not entirely sure how macOS would treat such a device without VT-D.

--------------

I do own a Thunderbolt 3 dock with an i210 NIC, however no Thunderbolt/Thunderbolt 2 cables or Thunderbolt2-3 adapters so can't verify this at this very moment with local hardware.
* I believe the local London Drugs does have some in stock, so might splurge and test on my MacBookPro8,2

--------------

Can you answer the following:

1. Does cold boot with ethernet connected result in the kernel panic?
2. Does this dock exhibit similar symptoms on Catalina or older?
3. Does the panic occur when ethernet is connected before plugging the dock in?
4. Does the panic occur without the router? ie. local network between 2 Macs via Ethernet

**Comment by campodit** [comment]
1. Yes, kernel panic right after typing the password on cold boot
2. I installed Catalina externally leaving the same OpenCore configuration and it works!
3. Yes, I connected the ethernet cable first before connecting the thunderbolt cable and the problem is the same
4. Yes, I shared the connection of my MacbookPro11,1 and kernel panic happen

**Comment by khronokernel** [comment]
Hm unfortunate, was hoping we'd find a loop hole on avoiding an outright panic 

------
With regards to troubleshooting, it would be difficult to remotely debug this issue. I'll most likely purchase the hardware sometime this week and try to replicate this locally.

I do have a test build you can try for the time being, however not promising much:

* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/5168092910/artifacts/156602159
  * You'll need to be signed in to download (ie. viewing from an email), otherwise 404

You should see this line when building:
```
- Adding experimental I210 Kext
```

**Comment by khronokernel** [comment]
Oh and ensure you have a backup OpenCore install in the event this build kernel panics on boot

**Comment by campodit** [comment]
Ok, I have the line "- Adding experimental I210 Kext"
The iMac freezes as soon as the apple starts loading:

![IMG_3318](https://user-images.githubusercontent.com/82968162/152402465-034abac2-16b6-4ee6-8981-e11659a3fb49.JPG)

Verbose :
![IMG_3317](https://user-images.githubusercontent.com/82968162/152402508-54fbc7af-54ae-410d-a587-53caeb7d3ab6.JPG)

I tried with SIP disabled, same result

Same thing on my other iMac with Big Sur and K610M

**Comment by campodit** [comment]
I install OCLP on a USB key so no problem to reboot

**Comment by khronokernel** [comment]
Ah I see the issue, Xcode botched integers in plists (coverts them to real for some reason). Try this build:
* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/5169984732/artifacts/156714326

**Comment by campodit** [comment]
Stuck on the apple logo, no progress bar
I test each time on the 2 iMac
![IMG_3319](https://user-images.githubusercontent.com/82968162/152419685-ad2c888e-6ce1-4d62-b03b-33ca6602820c.JPG)

**Comment by khronokernel** [comment]
With a bit of elbow grease, Ethernet looks to be working quite nicely:
![Screen Shot 2022-02-09 at 5 57 40 PM](https://user-images.githubusercontent.com/48863253/153324878-a37411a8-4c0e-416f-a9d3-62557d963b66.png)

Will push the code shortly

**Comment by Ausdauersportler** [comment]
Thank you!
Can confirm it works and the crash on plug is gone.

![ThunderboltDockEthernet](https://user-images.githubusercontent.com/71768134/153373697-a95ca750-d06c-4cf7-b10e-11f11244db29.png)

(iMac12,2, Elgato Thunderbolt 2 dock)

**Comment by campodit** [comment]
Thank you !! it works perfectly now 🎉
