### ISSUE TITLE
Card reader stopped working 

### ISSUE THREAD

**Issue by n3xus1** [dortania/OpenCore-Legacy-Patcher#978]
### Machine Model

MacBookPro8,1

### Application Version

Latest Build (nightly)

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

some time around 12.2.1 the card reader stopped working
I have checked with forum members and some have confirmed.
I have tested my card reader using 10.12.6 and it still works 
I have attached outputs of ioreg for both 12.3B and 10.12.6

thanks

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

[ioreg_MBP8.1_12.3.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/8127231/ioreg_MBP8.1_12.3.txt)
[ioreg_MBP8.1_10.12.6.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/8127232/ioreg_MBP8.1_10.12.6.txt)

**Comment by khronokernel** [comment]
Thank you for the report, I can confirm that on a MacBookPro8,2 running 12.3 that the SDXC controller no longer supports SD card detection. In addition, I've verified that 11.6.1 does have functional SDXC so this issue is limited to Monterey.

This issue doesn't affect Ivy Bridge and newer Macs with SDXC controllers (Sandy and newer all use the `14e4:16bc` chipsets). This leads me to believe that when MacBookPro18,x was added to Monterey, Apple implemented VT-D mapping similar to the Broadcom BCM5701 and Intel i210 situation.

While a bit strange this wasn't implemented in Big Sur (AppleSDXC was already compiled for the `arm64e` target), some engineer probably realized this when reworking the SDXC stack for the 14"/16" systems.

-------

With regards to resolving this, we'll simply out-probe AppleSDXC with an older variant without the VT-D enforcement:

![Screen Shot 2022-02-23 at 1 38 09 PM](https://user-images.githubusercontent.com/48863253/155406847-3be8620d-c3f3-44c0-ad0e-cc6e5b10d362.png)

I'll push this to mainline shortly, however the kext has been attached for completeness:

* [CtlnaSDXC-v1.0.0.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/8127765/CtlnaSDXC-v1.0.0.zip)
